#include "fontconvertcore.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>
#include <QTextStream>
#include <QVector>

#include <ft2build.h>
#include FT_FREETYPE_H

namespace {

constexpr quint16 kTransparentRgba1555 = 0x0000;
constexpr quint16 kBlackRgba1555 = 0xffff;
constexpr int kTextGrayThreshold = 16;

QString charName(QChar ch)
{
    switch (ch.unicode()) {
    case '0': return QStringLiteral("num0");
    case '1': return QStringLiteral("num1");
    case '2': return QStringLiteral("num2");
    case '3': return QStringLiteral("num3");
    case '4': return QStringLiteral("num4");
    case '5': return QStringLiteral("num5");
    case '6': return QStringLiteral("num6");
    case '7': return QStringLiteral("num7");
    case '8': return QStringLiteral("num8");
    case '9': return QStringLiteral("num9");
    case ':': return QStringLiteral("colon");
    case '-': return QStringLiteral("minus");
    case ' ': return QStringLiteral("blank");
    default:
        return QStringLiteral("u%1").arg(ch.unicode(), 4, 16, QChar('0'));
    }
}

QString arrayName(QChar ch, const QString &suffix)
{
    return QStringLiteral("%1%2_rgba").arg(charName(ch), suffix);
}

bool isValidIdentifierSuffix(const QString &suffix)
{
    static const QRegularExpression suffixRegex(QStringLiteral("^[A-Za-z0-9_]*$"));
    return suffixRegex.match(suffix).hasMatch();
}

void drawBitmapTextToBuffer(const FT_Bitmap &bitmap,
                            QVector<quint16> &buffer,
                            int width,
                            int height,
                            int dstX,
                            int dstY)
{
    for (int y = 0; y < static_cast<int>(bitmap.rows); ++y) {
        const unsigned char *row = nullptr;
        if (bitmap.pitch >= 0) {
            row = bitmap.buffer + y * bitmap.pitch;
        } else {
            row = bitmap.buffer + (static_cast<int>(bitmap.rows) - 1 - y) * (-bitmap.pitch);
        }

        for (int x = 0; x < static_cast<int>(bitmap.width); ++x) {
            const int px = dstX + x;
            const int py = dstY + y;
            if (px < 0 || px >= width || py < 0 || py >= height) {
                continue;
            }

            const quint8 gray = row[x];
            if (gray < kTextGrayThreshold) {
                continue;
            }

            buffer[py * width + px] = kBlackRgba1555;
        }
    }
}

bool renderOneChar(FT_Face face,
                   QTextStream &out,
                   QChar ch,
                   int width,
                   int height,
                   int fontSize,
                   const QString &suffix,
                   QString *errorMessage)
{
    QVector<quint16> buffer(width * height, kTransparentRgba1555);

    if (ch != QChar(' ')) {
        FT_Error error = FT_Set_Pixel_Sizes(face, 0, static_cast<FT_UInt>(fontSize));
        if (error != 0) {
            *errorMessage = QStringLiteral("FT_Set_Pixel_Sizes failed, ret=%1").arg(error);
            return false;
        }

        error = FT_Load_Char(face, static_cast<FT_ULong>(ch.unicode()), FT_LOAD_RENDER);
        if (error != 0) {
            *errorMessage = QStringLiteral("FT_Load_Char failed: '%1', ret=%2").arg(ch).arg(error);
            return false;
        }

        FT_GlyphSlot slot = face->glyph;
        const FT_Bitmap &bitmap = slot->bitmap;
        const int drawX = (width - static_cast<int>(bitmap.width)) / 2;
        const int drawY = (height - static_cast<int>(bitmap.rows)) / 2;

        drawBitmapTextToBuffer(bitmap, buffer, width, height, drawX, drawY);
    }

    if (ch == QChar(' ')) {
        out << "/* space */\n";
    } else {
        out << "/* " << ch << " */\n";
    }

    out << "static const unsigned short " << arrayName(ch, suffix) << "[] = {\n";
    for (int y = 0; y < height; ++y) {
        out << "\t";
        for (int x = 0; x < width; ++x) {
            out << QStringLiteral("0x%1").arg(buffer[y * width + x], 4, 16, QChar('0'));
            if (!(y == height - 1 && x == width - 1)) {
                out << ", ";
            }
            if ((x + 1) % 16 == 0 && x != width - 1) {
                out << "\n\t";
            }
        }
        out << "\n";
    }
    out << "};\n\n";

    return true;
}

void writeHeaderPrefix(QTextStream &out, int width, int height)
{
    out << "#ifndef __SDK_VIDEO_OSD_DATA_H__\n";
    out << "#define __SDK_VIDEO_OSD_DATA_H__\n\n";
    out << "#include <stdint.h>\n\n";
    out << "#define NUM_WIDTH " << width << "\n";
    out << "#define NUM_HEIGHT " << height << "\n";
    out << "#define NUM_BPP 16\n";
    out << "#define NUM_BYTE_PER_PIXEL 2\n\n";
    out << "/*\n";
    out << " * Auto generated by BSDToolGather font converter.\n";
    out << " * Pixel format: RGBA1555\n";
    out << " * Storage type : unsigned short\n";
    out << " *\n";
    out << " * bit15    : A\n";
    out << " * bit14~10 : R\n";
    out << " * bit9~5   : G\n";
    out << " * bit4~0   : B\n";
    out << " *\n";
    out << " * transparent : 0x0000\n";
    out << " * black text  : 0xffff (-1)\n";
    out << " *\n";
    out << " * no mask\n";
    out << " * no shadow\n";
    out << " */\n\n";
}

} // namespace

FontConvertCore::Result FontConvertCore::convert(const Options &options)
{
    Result result;

    if (options.format != RGBA1555) {
        result.errorMessage = QStringLiteral("当前只支持 RGBA1555 格式");
        return result;
    }
    if (options.fontPath.trimmed().isEmpty()) {
        result.errorMessage = QStringLiteral("请选择字体文件");
        return result;
    }
    if (options.outputPath.trimmed().isEmpty()) {
        result.errorMessage = QStringLiteral("请输入输出文件名");
        return result;
    }
    if (options.width <= 0 || options.height <= 0 || options.fontSize <= 0) {
        result.errorMessage = QStringLiteral("宽度、高度、字号必须大于 0");
        return result;
    }
    if (options.chars.isEmpty()) {
        result.errorMessage = QStringLiteral("请输入需要转换的字符");
        return result;
    }
    if (!isValidIdentifierSuffix(options.suffix)) {
        result.errorMessage = QStringLiteral("数组后缀只能包含字母、数字和下划线");
        return result;
    }
    if (!QFileInfo::exists(options.fontPath)) {
        result.errorMessage = QStringLiteral("字体文件不存在：%1").arg(options.fontPath);
        return result;
    }

    FT_Library library = nullptr;
    FT_Face face = nullptr;

    FT_Error error = FT_Init_FreeType(&library);
    if (error != 0) {
        result.errorMessage = QStringLiteral("FT_Init_FreeType failed, ret=%1").arg(error);
        return result;
    }

    error = FT_New_Face(library, QFile::encodeName(options.fontPath).constData(), 0, &face);
    if (error != 0) {
        result.errorMessage = QStringLiteral("FT_New_Face failed: %1, ret=%2").arg(options.fontPath).arg(error);
        FT_Done_FreeType(library);
        return result;
    }

    QFile outputFile(options.outputPath);
    const QFileInfo outputInfo(outputFile);
    const QDir outputDir = outputInfo.dir();
    if (!outputDir.exists() && !QDir().mkpath(outputDir.absolutePath())) {
        result.errorMessage = QStringLiteral("无法创建输出目录：%1").arg(outputDir.absolutePath());
        FT_Done_Face(face);
        FT_Done_FreeType(library);
        return result;
    }

    if (!outputFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        result.errorMessage = QStringLiteral("无法创建输出文件：%1").arg(options.outputPath);
        FT_Done_Face(face);
        FT_Done_FreeType(library);
        return result;
    }

    QTextStream out(&outputFile);
    writeHeaderPrefix(out, options.width, options.height);

    for (const QChar &ch : options.chars) {
        QString errorMessage;
        if (!renderOneChar(face,
                           out,
                           ch,
                           options.width,
                           options.height,
                           options.fontSize,
                           options.suffix,
                           &errorMessage)) {
            outputFile.close();
            QFile::remove(options.outputPath);
            result.errorMessage = errorMessage;
            FT_Done_Face(face);
            FT_Done_FreeType(library);
            return result;
        }
        ++result.glyphCount;
    }

    out << "#endif\n";
    outputFile.close();

    FT_Done_Face(face);
    FT_Done_FreeType(library);

    result.success = true;
    result.messages.append(QStringLiteral("字模转换完成：%1").arg(options.outputPath));
    result.messages.append(QStringLiteral("格式：RGBA1555"));
    result.messages.append(QStringLiteral("尺寸：%1 x %2，字号：%3，字符数：%4")
        .arg(options.width)
        .arg(options.height)
        .arg(options.fontSize)
        .arg(result.glyphCount));
    return result;
}
